//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDR_AD                          101
#define IDD_GAME_PLAZA                  102
#define IDD_SHORT_MESSAGE               110
#define IDD_FIND_USER                   111
#define IDD_SHOW                        112
#define IDD_MANAGER_RIGHT               115
#define IDR_MAINFRAME                   128
#define IDS_MAIN_TITLE                  129
#define IDD_GAME_ROOM                   130
#define IDD_LOGON                       132
#define IDR_MENU                        134
#define IDD_CONTROL_BAR                 135
#define IDD_STATUS                      136
#define IDB_CONNECT_STATUS              137
#define IDB_CONNECT_BG                  138
#define IDB_SERVER_LIST_IMAGE           142
#define IDB_USER_STATUS                 144
#define IDB_BT_EXPESSION                147
#define IDB_BT_SEND_CHAT                149
#define IDB_BT_COLOR_SET                150
#define IDB_BT_CLEAN_SCREEN             151
#define IDB_FRAME_MIN                   158
#define IDB_FRAME_CLOSE                 159
#define IDB_FRAME_MAX                   160
#define IDB_BAR_ITEM                    163
#define IDD_OPTION                      181
#define IDD_OPTION_TABLE_RULE           182
#define IDB_OP_NORMAL                   183
#define IDD_OPTION_SYSTEM               183
#define IDB_OP_HOT                      184
#define IDB_OP_ACTIVE                   185
#define IDC_HAND_CUR                    209
#define IDB_TABLE_LOCK                  230
#define IDB_TABLE_READY                 231
#define IDB_FRAME_BT_BUTTON_4           247
#define IDB_FRAME_BT_BUTTON_3           248
#define IDB_FRAME_BT_BUTTON_2           249
#define IDB_FRAME_BT_BUTTON_1           250
#define IDB_BT_SEARCH_USER              251
#define IDB_BT_AUTO_JOIN                252
#define IDB_BAR_BUTTON_FRIEND           253
#define IDB_BAR_BUTTON_NUMBER           255
#define IDB_BAR_BUTTON_SET              256
#define IDB_BAR_BUTTON_PERSIONSET       257
#define IDB_BAR_ITEM_HOME               258
#define IDB_LEFT_VIEW_MMM               260
#define IDB_LEFT_VIEW_MTM               261
#define IDD_SEND_WARNING                262
#define IDB_FRAME_BT_BUTTON_6           263
#define IDB_FRAME_BT_BUTTON_7           264
#define IDD_REGISTER                    266
#define IDD_MANAGER_MESSAGE             267
#define IDD_MANAGER_SERVER              268
#define IDD_DIALOG1                     282
#define IDB_FRAME_TL                    283
#define IDB_FRAME_TM                    284
#define IDB_FRAME_TR                    285
#define IDD_DIALOG2                     285
#define IDB_FRAME_ML                    286
#define IDB_FRAME_MR                    287
#define IDB_FRAME_BL                    290
#define IDB_FRAME_BM                    291
#define IDB_STATUS_L                    293
#define IDB_STATUS_M                    294
#define IDB_BG_MAIN                     295
#define IDB_BG_MAIN2                    297
#define IDB_CHAT_TL                     305
#define IDB_CHAT_TM                     306
#define IDB_CHAT_TR                     307
#define IDB_QQSHOW_L                    308
#define IDB_QQSHOW_R                    309
#define IDB_QQSHOW_B                    310
#define GAMELIST_B2                     311
#define GAMELIST_T3                     319
#define ROOMLIST_T                      320
#define ROOMLIST_L                      321
#define ROOMLIST_R                      322
#define ROOMLIST_B                      323
#define ROOMLIST_S_T                    324
#define ROOMLIST_S_M                    325
#define ROOMLIST_S_B                    326
#define ROOMLIST_S_THUMB                327
#define ROOMLIST_BTN                    328
#define GAMELIST_B3                     329
#define USERLIST_T                      330
#define GameList_T                      330
#define USERLIST_L                      331
#define USERLIST_R                      332
#define USERLIST_B                      333
#define USERLIST_S_T                    334
#define USERLIST_S_M                    335
#define USERLIST_S_B                    336
#define USERLIST_S_THUMB                337
#define USERLIST_BTN                    338
#define IDB_LOGON_FINDPASS              342
#define IDB_LOGON_WEBSITE               343
#define IDB_LOGON_REG                   344
#define IDB_GAME_ITEM_DEFAULT           350
#define IDB_ICO_DDZ                     500
#define IDB_ICO_ZJH                     501
#define IDB_ICO_MJ                      502
#define IDB_ICO_SH                      503
#define IDB_ICO_SDH                     504
#define IDB_ICO_YJYX                    505
#define USERLIST_T1                     506
#define GAMELIST_T2                     506
#define ROOMLIST_R1                     507
#define ROOMLIST_L1                     508
#define IDB_FRAME_BT_BUTTON_5           509
#define USERLIST_INFO                   510
#define USERLIST_WEB                    511
#define USERLIST_TOP                    512
#define USERLIST_ROOM1                  513
#define USERLIST_ROOM2                  514
#define USERLIST_ROOM3                  515
#define USERLIST_ROOM4                  516
#define USERLIST_ROOM5                  517
#define USERLIST_ROOM6                  518
#define USERLIST_ROOMEXIT               519
#define USERLIST_WEB1                   520
#define TABCARD                         520
#define IDC_CHAT_MESSAGE                1004
#define IDC_TABLE_PASSWORD              1004
#define IDC_SERVER                      1005
#define IDC_ACCOUNTS                    1006
#define IDC_PASSWORD                    1007
#define IDC_REMEMBER_PASSWORD           1008
#define IDC_DELETE_RECORD               1009
#define IDC_SEND_SHORT                  1010
#define IDC_NET_OPTION                  1011
#define IDC_PASSWORD2                   1011
#define IDC_BIND_USER                   1011
#define IDC_REGISTER                    1012
#define IDC_RECV_MESSAGE                1012
#define IDC_BIND_GAME                   1012
#define IDC_LOGON_TYPE                  1013
#define IDC_SEND_MESSAGE                1013
#define IDC_NAME                        1013
#define IDC_FORGET                      1013
#define IDC_MAIN_PAGE                   1014
#define IDC_ACCID                       1014
#define IDC_PASSWORD_PROTECT            1015
#define IDC_GET_PASSWORD                1016
#define IDC_GET_PASSWORD2               1017
#define IDC_ApplyAccount                1017
#define IDC_PROXY_TYPE                  1018
#define IDC_PROXY_SERVER                1019
#define IDC_PROXY_USER                  1020
#define IDC_PROXY_PORT                  1021
#define IDC_PROXY_PASS                  1022
#define IDC_LIST                        1022
#define IDC_BORDER                      1023
#define IDC_USER_ID                     1024
#define IDC_CLOSE                       1025
#define IDC_TYPE_NAME                   1026
#define IDC_SERVER_LIST                 1027
#define IDC_PLAZA                       1029
#define IDC_BRING_TABLE_PASSWORD        1029
#define IDC_COMPANION_MANAGER           1030
#define IDC_SYSTEM_OPTION               1031
#define IDC_QUIT_GAME                   1034
#define IDC_SHOW_CLOSE                  1035
#define IDC_SWITCH_ACCOUNTS             1036
#define IDC_VOR_SPLITER                 1039
#define IDC_VIEW_ITEM1                  1042
#define IDC_CHAT_INPUT                  1043
#define IDC_VIEW_ITEM2                  1043
#define IDC_VIEW_ITEM3                  1044
#define IDC_VIEW_ITEM4                  1045
#define IDC_SEND_CHAT                   1046
#define IDC_EXPRESSION                  1047
#define IDC_PHRASE                      1048
#define IDC_COLOR_SET                   1049
#define IDC_CLEAN_SCREEN                1050
#define IDC_LIMIT_IP                    1052
#define IDC_LIMIT_FLEE_RATE             1053
#define IDC_FLEE_RATE                   1054
#define IDC_LIMIT_SCORE                 1055
#define IDC_USER_LIST                   1056
#define IDC_LIMIT_NET_DELAY             1056
#define IDC_NET_DELAY                   1057
#define IDC_LIMIT_DETEST                1060
#define IDC_LIMIT_WIN_RATE              1061
#define IDC_WIN_RATE                    1062
#define IDC_SCORE_LESS                  1063
#define IDC_SAVE_NONE                   1065
#define IDC_SAVE_ACCOUNTS               1066
#define IDC_SAVE_ACCOUNTS_AND_PASS      1067
#define IDC_CHAT_OBJECT                 1068
#define IDC_USER_FACE                   1073
#define IDC_PRIVIEW                     1074
#define IDC_WARNING_MESSAGE             1077
#define IDC_ROOM_CHAT                   1078
#define IDC_GAME_MESSAGE                1078
#define IDC_GAME_CHAT                   1079
#define IDC_ROOM_MESSAGE                1079
#define IDC_SEND_WISPER                 1080
#define IDC_SYSTEM_MESSAGE              1080
#define IDC_PLAY_GAME                   1081
#define IDC_LOOKON_GAME                 1082
#define IDC_SET_SHALL_CLOSE             1082
#define IDC_LIMIT_WISPER                1083
#define IDC_LIMIT_ROOM_CHAT             1084
#define IDC_LIMIT_ENTER_GAME            1085
#define IDC_LIMIT_GAME_CHAT             1086
#define IDC_TAB1                        1086
#define IDC_LOGIN_SERVER_LABEL          1086
#define IDC_SCORE_MAX                   1087
#define IDC_LIMIT_ENTER_ROOM            1087
#define IDC_ACCOUNT_LABEL               1087
#define IDC_PASSWORD_LABEL              1088
#define IDC_CHECK1                      1089
#define IDC_BGSOUND                     1090
#define IDC_BUTTON1                     1091
#define IDC_SKIN                        1091
#define IDC_RESET_SHALL_CLOSE           1094
#define IDC_ALLOW_WISPER                1095
#define IDC_ALLOW_ROOM_CHAT             1096
#define IDC_ALLOW_ENTER_GAME            1097
#define IDC_ALLOW_GAME_CHAT2            1098
#define IDC_ALLOW_GAME_CHAT             1098
#define IDC_ALLOW_ENTER_ROOM            1099
#define IDM_LOGON_PLAZA                 32772
#define IDM_CONNECT_SERVER              32774
#define IDM_CANCEL_CONNECT              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
